### ISSUE TITLE
Improve django-select2 usage

### ISSUE THREAD

**Issue by Far3t** [blatinier/onestpasdespigeons#107]
Add a spinner to show that the search is in progress while looking for a product.

**Comment by blatinier** [comment]
Ok, so… There is a « Loading » text displaying on searching data.
It never showed because requests were sent too fast and it created a shitstrom in the fan…

I added a delay of 500ms before sending request after key pressed (if another key was pressed before the 500ms, it resets the counter).
The result is that we see better the « Loading » status (even if we still see the « Could not fetch » stuff time to time)
And the requests are a bit faster (since the server does not have to search 10 times but only one for stuff)

Still:
 - The time to fetch stuff is not great (~ 1.5s/2s)
 - i18n is missing [see here](http://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.conf.Select2Conf.I18N_PATH)

**Comment by Far3t** [comment]
Have a look at https://github.com/zombodb/zombodb to try to have faster requests / fetch.

**Comment by blatinier** [comment]
We can start by a simple GIN index in pgsql without adding the ES part… We don't need complex query, we don't need aggregations, we have a small amount of data… really no ES is good ;)

**Comment by blatinier** [comment]
For the record:

    >>> timeit.timeit("t=''.join([random.choice('azertyuiopmlkjhgfdsqwxcvbn') for i in range(random.randint(1,10))]);list(Product.objects.filter(Q(product_name__icontains=t) | Q(brands__icontains=t))[0:25])",setup="from weights.models import Product;from django.db.models import Q;import random;",number=100)
    32.0371074154973

It means ~0.3s per query. Which is not great, but not the main problem IMO…

**Comment by blatinier** [comment]
https://github.com/jazzband/silk

**Comment by blatinier** [comment]
Ok, see http://pigeon.latinier.fr/silk/request/2d67deb3-690f-4108-9b46-c9d479e2f871/sql/ for the real executed sql. In the previous bench we were missing the `.distinct` which adds a good `x2` and the `.upper` filtering which adds also a `x2`.
I found similar results with this:

    >>> timeit.timeit("t=''.join([random.choice('azertyuiopmlkjhgfdsqwxcvbn') for i in range(random.randint(1,10))]);list(Product.objects.distinct().annotate(product_name_up=Upper('product_name')).annotate(brands_up=Upper('brands')).filter(Q(product_name_up__icontains=t.upper()) | Q(brands_up__icontains=t.upper()))[0:25])",setup="from weights.models import Product;from django.db.models import Q;from django.db.models.functions import Upper;import random;",number=100)
    80.82303868234158

**Comment by blatinier** [comment]
The solution for now would be to drop the django-select2 plugin and do it by hand to query exactly like we want.
