### ISSUE TITLE
image balance

### ISSUE THREAD

**Issue by melmelboo** [blatinier/onestpasdespigeons#82]
ajouter une image de balance standard pour les gens qui ne prennent pas de photo

**Comment by Far3t** [comment]
A simple photo of scales? Or an SVG picture?

**Comment by blatinier** [comment]
A picture. I have it in my mail.
-------- Message d'origine --------De : Fabien Bourrel <notifications@github.com> Date : 04/09/2017  19:10  (GMT+02:00) À : blatinier/onestpasdespigeons <onestpasdespigeons@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : Re: [blatinier/onestpasdespigeons] image balance (#82) 
A simple photo of scales? Or an SVG picture?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/blatinier/onestpasdespigeons","title":"blatinier/onestpasdespigeons","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/blatinier/onestpasdespigeons"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Far3t in #82: A simple photo of scales? Or an SVG picture?"}],"action":{"name":"View Issue","url":"https://github.com/blatinier/onestpasdespigeons/issues/82#issuecomment-326995691"}}}

**Comment by blatinier** [comment]
In yours too. Image balance rouge.
